version: "3.7"
services:
    db:
        image: ais_postgres:devel
        # restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        ports:
            - "5432:5432"
        deploy:
            placement:
                constraints:
                    - node.role == manager
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        command:
            - postgres
            - -c
            - 'tcp_keepalives_idle=600'
            - -c
            - 'tcp_keepalives_interval=30'
            - -c
            - 'tcp_keepalives_count=10'
    receiver:
        image: ais_back:devel
        networks:
            - backend
        command: ["/init.d/init.sh", "startservices"]
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        secrets:
            - aishubapi_username
    app:
        image: ais_front:devel
        volumes:
            - ais_front:/app
        networks:
            - backend
            - frontend
        command: ["/init.d/init.sh"]
        environment:
            POSTGRES_HOST: db
        ports:
            - "4000:4000"

networks:
    backend:
    frontend:
secrets:
    aishubapi_username:
        file: ../../secrets/devel/aishubapi_username.txt
volumes:
    db-data:
    ais_front:
        external: true
