# Generated by Django 2.2.4 on 2019-08-22 16:21

import django.contrib.gis.db.models.fields
from django.db import migrations

from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190822_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='message',
            name='longitude',
        ),
        migrations.AddField(
            model_name='message',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(45.6, 25.1), geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
