version: "3.7"
services:
    db:
        image: postgres-ais
        # restart: always
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        ports:
            - "5432:5432"
        deploy:
            placement:
                constraints:
                    - node.role == manager
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        command:
            - postgres
            - -c
            - 'tcp_keepalives_idle=600'
            - -c
            - 'tcp_keepalives_interval=30'
            - -c
            - 'tcp_keepalives_count=10'
    aisreceiver:
        image: ais_back
        networks:
            - backend
        command: ["/init.sh", "startservices"]
        environment:
            POSTGRES_HOST: db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        # not supported for docker swarm
        # depends_on:
        #     - db
    # geoserver:
    #     image: kartoza/geoserver
    #     volumes:
    #         - geoserver-data:/opt/geoserver/data_dir
    #     networks:
    #         - backend
    #     environment:
    #         STABLE_EXTENSIONS: css-plugin
    #     ports:
    #         - "8600:8080"

networks:
    backend:
volumes:
    db-data:
    # geoserver-data:
    #     external: true
