version: "3.7"
services:
    db:
        image: ais_postgres:prod
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - backend
        ports:
            - ":5432"
        deploy:
            placement:
                constraints:
                    - node.role == manager
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
        command:
            - postgres
            - -c
            - 'tcp_keepalives_idle=600'
            - -c
            - 'tcp_keepalives_interval=30'
            - -c
            - 'tcp_keepalives_count=10'
        secrets:
            - postgres_user
            - postgres_password
    receiver:
        image: ais_back:prod
        networks:
            - backend
        command: ["/init.d/init.sh", "startservices"]
        environment:
            POSTGRES_HOST: db
        secrets:
            - postgres_user
            - postgres_password
            - django_secret
            - aishubapi_username
    app:
        image: ais_front:prod
        networks:
            - backend
            - frontend
        command: ["/init.d/init.sh"]
        environment:
            POSTGRES_HOST: db
            PORT: 4000
        ports:
            - "80:4000"
        secrets:
            - elixir_secret
            - postgres_user
            - postgres_password
            - back_database_host
            - front_database_host

networks:
    backend:
    frontend:
secrets:
    postgres_user:
        file: ../../secrets/prod/postgres_user.txt
    postgres_password:
        file: ../../secrets/prod/postgres_password.txt
    back_database_host:
        file: ../../secrets/prod/back_database_host.txt
    front_database_host:
        file: ../../secrets/prod/front_database_host.txt
    django_secret:
        file: ../../secrets/prod/django_secret.txt
    elixir_secret:
        file: ../../secrets/prod/elixir_secret.txt
    aishubapi_username:
        file: ../../secrets/prod/aishubapi_username.txt
volumes:
    db-data:
