version: 1
formatters:
    default:
        format: '{asctime} [{levelname}] @ {name}.{funcName}() {message}'
        style: '{'
    brief:
        format: '{asctime} [{levelname}] {message}'
        style: '{'
handlers:
    precise:
        class: logging.FileHandler
        formatter: brief
        filename: logs/ais.log
        mode: w
        level: INFO
    core:
        class: logging.FileHandler
        formatter: brief
        filename: logs/core.log
        mode: w
        level: DEBUG
    aisreceiver:
        class: logging.FileHandler
        formatter: brief
        filename: logs/aisreceiver.log
        mode: w
        level: DEBUG
    console:
        class: logging.StreamHandler
        formatter: brief
        level: DEBUG
loggers:
    aisreceiver:
        level: DEBUG
        handlers: [aisreceiver, console]
    core:
        level: DEBUG
        handlers: [core, console]
root:
    level: INFO
    handlers: [precise]
