# Generated by Django 2.2.4 on 2019-09-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='core_message_uniq_mmsi_timedesc',
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('mmsi', 'time'), name='core_message_uniq_mmsi_time'),
        ),
    ]
