# Generated by Django 2.2.4 on 2019-09-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mmsi', '-time'], name='core_messag_mmsi_b36d69_idx'),
        ),
    ]
