# Generated by Django 2.2.4 on 2019-08-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='imo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='mmsi',
            field=models.IntegerField(),
        ),
    ]
