# Generated by Django 2.2.4 on 2019-09-15 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190911_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastMessage',
            new_name='ShipInfos',
        ),
    ]
