# Generated by Django 2.2.4 on 2019-09-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190915_1426'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='core_messag_mmsi_b36d69_idx',
        ),
        migrations.AlterField(
            model_name='message',
            name='mmsi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ShipInfos'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mmsi', '-time'], name='core_message_mmsi_timedesc_idx'),
        ),
    ]
