# Generated by Django 2.2.4 on 2019-09-15 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190915_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='mmsi',
            field=models.ForeignKey(db_column='mmsi', on_delete=django.db.models.deletion.DO_NOTHING, to='core.ShipInfos'),
        ),
    ]
