# Generated by Django 2.2.4 on 2019-09-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190915_1539'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='core_message_mmsi_timedesc_idx',
        ),
    ]
