# Generated by Django 2.2.12 on 2020-05-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190917_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('summary', models.CharField(max_length=128)),
                ('details', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
        ),
    ]
