# Generated by Django 2.2.12 on 2020-05-14 11:56

from django.db import migrations

from core.models import ShipType


def create_all_shiptype(apps, schema_editor) -> None:
    ShipType.objects.prepopulate()


def delete_all_shiptype(apps, schema_editor) -> None:
    ShipType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shiptype'),
    ]

    operations = [
        migrations.RunPython(create_all_shiptype, delete_all_shiptype),
    ]
