# Generated by Django 2.2.12 on 2020-05-12 21:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipGeometries',
            fields=[
                ('mmsi', models.IntegerField(primary_key=True, serialize=False)),
                ('wkt_shape', models.CharField(blank=True, default='', max_length=256)),
                ('path', django.contrib.gis.db.models.fields.LineStringField(blank=True, default=None, geography=True, null=True, srid=4326)),
                ('last_update', models.DateTimeField()),
            ],
        ),
    ]
