# Generated by Django 2.2.12 on 2020-05-12 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipgeometries',
            name='mmsi',
            field=models.ForeignKey(db_column='mmsi', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.ShipInfos'),
        ),
    ]
