# Generated by Django 2.2.12 on 2020-05-14 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoserver', '0005_geoserver_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipgeometries',
            old_name='height',
            new_name='length',
        ),
    ]
